/* Auto-generated by genmsg_cpp for file /home/guillermo/anaconda3/envs/CenterNet/CenterNet/src/ROS/src/centernet_ros/msg/detecciones.msg */
#ifndef CENTERNET_ROS_MESSAGE_DETECCIONES_H
#define CENTERNET_ROS_MESSAGE_DETECCIONES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace centernet_ros
{
template <class ContainerAllocator>
struct detecciones_ {
  typedef detecciones_<ContainerAllocator> Type;

  detecciones_()
  : data()
  {
  }

  detecciones_(const ContainerAllocator& _alloc)
  : data(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  data;


  typedef boost::shared_ptr< ::centernet_ros::detecciones_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::centernet_ros::detecciones_<ContainerAllocator>  const> ConstPtr;
}; // struct detecciones
typedef  ::centernet_ros::detecciones_<std::allocator<void> > detecciones;

typedef boost::shared_ptr< ::centernet_ros::detecciones> deteccionesPtr;
typedef boost::shared_ptr< ::centernet_ros::detecciones const> deteccionesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::centernet_ros::detecciones_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::centernet_ros::detecciones_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace centernet_ros

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::centernet_ros::detecciones_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::centernet_ros::detecciones_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::centernet_ros::detecciones_<ContainerAllocator> > {
  static const char* value() 
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const  ::centernet_ros::detecciones_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::centernet_ros::detecciones_<ContainerAllocator> > {
  static const char* value() 
  {
    return "centernet_ros/detecciones";
  }

  static const char* value(const  ::centernet_ros::detecciones_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::centernet_ros::detecciones_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] data\n\
\n\
";
  }

  static const char* value(const  ::centernet_ros::detecciones_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::centernet_ros::detecciones_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct detecciones_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::centernet_ros::detecciones_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::centernet_ros::detecciones_<ContainerAllocator> & v) 
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CENTERNET_ROS_MESSAGE_DETECCIONES_H

